### PR TITLE
Media control

### PR DESCRIPTION
**Pull request by vfcoelho**
Added media control for Chimera.
Also added .gitignore file and started getting BOT_TOKEN and CHANNEL_ID from local_credentials.py file, which was added to the .gidignore, solving the problem of pottential contributors tokens being commited.
Also added some eclipse project related .gitignore entries.
Added requirements.txt to organize dependencies.
Added input_commands.py file which can send keyboard input signals to OS (Windows)

### CODE REVIEW

**Comment by CedArctic** [comment]
@vfcoelho Thanks for your contribution! Many of these changes will make the project much more tidy. Could you though add a blank sample local_credentials.py ?

**Comment by vfcoelho** [comment]
Sure, will do.
I'll also add mute command that I forgot before PRing.

**Comment by vfcoelho** [comment]
Maybe a setup? That creates a text config file on the first execution. What do you think would be best?

**Comment by CedArctic** [comment]
@vfcoelho Agreed, a setup could possibly make things more complicated, maybe at some point later when the project gets bigger, a setup might be an advantage to have. I'm glad you liked the idea and it's been great to have you contribute with your great ideas!

**Comment by vfcoelho** [comment]
Thanks! It's been fun to contribute!

**Pull request merged**
