### PR TITLE
Chimera_logo

### PR DESCRIPTION
**Pull request by vlad4him**
The logo i thought about.

### CODE REVIEW

**Comment by DragosPopse** [comment]
Looks really nice. I think it fits with the discord theme. Let's see if the owner likes your work :)

**Comment by vlad4him** [comment]
I think this one would look better because of the contrast but chose any of them.

**Comment by CedArctic** [comment]
@vlad4him These look great. Indeed the contrast in the second one adds an extra flair to it. I'll wait to see some more of the submissions but either way that is some great work you've got there and I thank you for your contribution!

**Comment by vlad4him** [comment]
Thanks.Hope you choose the right one.

**Comment by CedArctic** [comment]
@vlad4him I think we're going to be using your latest design as our logo! Could you also add a commit to insert the image file in the README.md so we can merge the PR?

**Comment by vlad4him** [comment]
How do you want the image to be, at the top?

**Comment by CedArctic** [comment]
Yes, centered at the top.

**Comment by CedArctic** [comment]
@vlad4him Thanks for your great work! I'm merging the PR.

**Pull request merged**
