### PR TITLE
Linux-compatible media control, logging and file management features added

### PR DESCRIPTION
**Pull request by vfcoelho**
Did some refacotring on media control dependencies and it is now linux-friendly

### CODE REVIEW

**Comment by vfcoelho** [comment]
Tested on Ubuntu 18.04.1 LTS

**Comment by vfcoelho** [comment]
Also added a semaphore for shared memory management between threads of different commands, which will be useful in future development

**Comment by CedArctic** [comment]
@vfcoelho Wow that's a ton of great changes! Sorry for the late reply, things have been a bit busy around here lately. I'll dig into the code ASAP and let you know my thought. Thanks for contributing once more! 😄

**Comment by CedArctic** [comment]
@vfcoelho Everything seems in order. This is a massive step forward! Thank you so much for your PR! I'm merging the request. 😄

**Pull request merged**
