### PR TITLE
Add Linux Support

### PR DESCRIPTION
**Pull request by TGlide**
#1 

Instead of creating a separate linux file, I addedd support on chimera_windows.py . I suggest renaming it to chimera maybe?

Some commands require sudo to run on linux, so I added that information on README.md

Some methods I wasn't able to find a replacement to linux. I think TTS would be able by means of a python module,I can look into it too!

I created a helpers.py so I wouldn't make the main code dirty. It only has a helper function that returns the platform the script is running on.

### CODE REVIEW

**Comment by CedArctic** [comment]
Looks interesting. I would love to look into it a bit more, but for now I'm closing this PR as it contains your personal token and channel ID.

**Comment by CedArctic** [comment]
* Edit: Just push a new commit on top to restore the channel ID and token to the defaults and I'll check it out.

**Comment by TGlide** [comment]
Yes, I saw that, my bad. I think it's all good now!

**Comment by CedArctic** [comment]
@TGlide Nice work! At the moment I am looking into #8 and thinking of merging that first. Could you then maybe look into integrating what has been introduced with #8 as well?

**Comment by TGlide** [comment]
Yes, I'll look into it!

**Comment by TGlide** [comment]
Fixed some conflicts, will take a look at media control

**Comment by CedArctic** [comment]
@TGlide that's great! In the mean time since this PR has no conflicts, I will merge it and you can create a new one for porting media control and other features. Thanks for contributing!

**Comment by TGlide** [comment]
Sure thing! Glad I could help :)

**Pull request merged**
